In [1]:
import torch

In [6]:
 t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [4]:
t.size()

torch.Size([3, 4])

In [19]:
t.squeeze(1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [15]:
t.unsqueeze(2)

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [2.],
         [2.]],

        [[3.],
         [3.],
         [3.],
         [3.]]])

In [20]:
mat1 = torch.tensor([[1,2,3],
                    [5,7,8]])
mat2 = torch.tensor([[1,2],
                    [5,7],
                    [2,3]
                    ])

In [21]:
torch.mm(mat1,mat2)

tensor([[17, 25],
        [56, 83]])

In [24]:
for i in range(5,-1,-2):
    print(i)

5
3
1
